# Generated by Django 3.2 on 2021-04-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep_app', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizenprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Citizenprofile',
        ),
    ]
