# Generated by Django 3.2 on 2021-04-15 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ep_app', '0005_fir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_place', models.TextField()),
                ('Date_and_Time', models.DateTimeField()),
                ('Crime_Description', models.TextField()),
                ('complain_againts', models.TextField()),
                ('proof', models.FileField(null=True, upload_to='proof')),
                ('status', models.CharField(choices=[('Activate', 'Activate'), ('Inprocess', 'Inprocess'), ('Closed', 'Closed')], max_length=20)),
                ('Reason', models.CharField(max_length=256)),
                ('complain_Date_and_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
