# Generated by Django 3.2 on 2021-05-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep_app', '0008_crime_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_sub_category', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('crime_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep_app.crime_category')),
            ],
        ),
    ]
