# Generated by Django 3.2 on 2021-05-05 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep_app', '0009_crime_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='crime_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ep_app.crime_category'),
        ),
        migrations.AddField(
            model_name='fir',
            name='crime_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ep_app.crime_sub_category'),
        ),
    ]
