# Generated by Django 3.2 on 2021-05-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep_app', '0015_taluka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=256)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ep_app.city')),
                ('taluka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ep_app.taluka')),
            ],
        ),
    ]
