# Generated by Django 3.2 on 2021-05-06 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep_app', '0016_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_station',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ep_app.city'),
        ),
        migrations.AddField(
            model_name='police_station',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='police_station',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='police_station',
            name='taluka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ep_app.taluka'),
        ),
        migrations.AddField(
            model_name='police_station',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ep_app.village'),
        ),
        migrations.AlterField(
            model_name='police_station',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Inspector',
        ),
    ]
