# Generated by Django 3.2 on 2021-05-19 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ep_app', '0018_auto_20210506_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commissioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
                ('Age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('mobile_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commissioner_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
                ('date_of_birth', models.DateField()),
                ('mobile_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emergency_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
                ('Age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('mobile_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('police_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ep_app.police_station')),
            ],
        ),
        migrations.CreateModel(
            name='Inspector_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Missing_Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=256)),
                ('Photo', models.ImageField(upload_to='missing_persons')),
                ('Date_of_birth', models.DateField()),
                ('Age', models.IntegerField()),
                ('Nickname', models.CharField(blank=True, max_length=256, null=True)),
                ('weight', models.IntegerField()),
                ('height', models.CharField(max_length=10)),
                ('Skin_color', models.CharField(max_length=256)),
                ('Missing_Date', models.DateField()),
                ('Address', models.TextField()),
                ('Contact_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rules_Regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=256)),
                ('Document', models.FileField(upload_to='rules_regulation')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Officers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ep_app.constable')),
                ('inspector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ep_app.inspector_login')),
                ('police_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ep_app.police_station')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
                ('date_of_birth', models.DateField()),
                ('mobile_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='Photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='photos_videos/'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='photos_videos/'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complain',
            name='Date_and_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proof'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proof'),
        ),
        migrations.DeleteModel(
            name='Photos_Videos',
        ),
        migrations.AddField(
            model_name='service_officers',
            name='sub_inspector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ep_app.sub_inspector'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ep_app.inspector_login'),
        ),
        migrations.AddField(
            model_name='commissioner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ep_app.commissioner_login'),
        ),
    ]
